apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pthon
  janus-idp.io/tekton: pthon
  backstage.io/kubernetes-id: pthon
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pthon
resources:
- deployment.yaml
- route.yaml
- service.yaml
