apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pthon
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pthon 
  name: pthon
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pthon 
